### PR TITLE
Program Page

### PR DESCRIPTION
**Pull request by jagoncalves14**

### CODE REVIEW

**Comment by inesrosete** [comment]
What changes have you done in `seeds.json`?

**Comment by inesrosete** [comment]
> What changes have you done in `seeds.json`?

Ignore this comment

**Comment by inesrosete** [comment]
@jagoncalves14 check this issue :)

image

**Comment by luisiul359** [comment]
> @jagoncalves14 check this issue :)
> 
> image

Fixed in #153

**Comment by luisiul359** [comment]
@nancruz once you built on top of this, are you ok with this PR or you want to further review it?

**Review by luisiul359 — APPROVED** [review]

**Pull request merged**
