### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by inesrosete**

### CODE REVIEW

**Review by marado — CHANGES_REQUESTED** [review]
This is not the content of the License file, but the text you ought to place on top of each file.
The actual LICENSE file should be this: https://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by inesrosete** [comment]
🤦‍♂ corrected. Is it necessary to add the header to each file or `LICENSE` in root is enough?

**Comment by marado** [comment]
From http://www.apache.org/dev/apply-license.html :

In addition, a correct NOTICE file MUST be included in the same directory as the LICENSE file. Each original source document (code and documentation, but excluding the LICENSE and NOTICE files) SHOULD include a short license header at the top.

**Comment by inesrosete** [comment]
Done.

> The remainder of the NOTICE file is to be used for required third-party notices.
> The NOTICE file may also include copyright notices moved from source files submitted to the ASF.

Not sure what to add, therefore I left just the header text

**Pull request merged**
